# camera_preview.py
CAMERA_RESOLUTION = (1024, 768)

# hardware pins
LICKPORT_PIN = 21
WATER_SOLENOID_PIN = 8
AIRPUFF_SOLENOID_PIN = 10
FAKE_SOLENOID_PIN = 12
ENCODER_A_PIN = 24
ENCODER_B_PIN = 22
AIRPUFF_TTL_PULSE = 11
VIDEO_TTL_PULSE = 36

# data file prefixes
TTL_PREFIX = "ttl_data_"
PUFF_PREFIX = "puff_data_"
DIST_PREFIX = "distance_data_"
LICK_PREFIX = "lick_data_"
